version: "3.7"
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    volumes:
      - ./api/openapi.yml:/usr/share/nginx/html/openapi.yml
      - ./api/resources:/usr/share/nginx/html/resources
    environment:
      API_URL: openapi.yml
    ports:
      - "8080:8080"
  swagger-api:
    image: stoplight/prism:3
    container_name: swagger-api
    ports:
      - "8082:4010"
    command: mock -d -h 0.0.0.0 /openapi.yml
    volumes:
      - ./api/openapi.yml:/openapi.yml
      - ./api/resources:/resources
