openapi: 3.0.0
info:
  title: API
  description: openapi for flutter
  version: v1

servers:
  - url: http://localhost:8082/
paths:
  /users:
    $ref: "./resources/responses/users.yml"
  /users/{id}:
    $ref: "./resources/responses/user.yml"
